apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-pro-env
  labels:
    app: gke-pro-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-pro-env
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gke-pro-env
    spec:
      containers:
      - name: gke-pro-env
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000
