apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: gke-test-selenium
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: gke-test-selenium
    spec:
      containers:
      - name: gke-test-selenium
        image: gcr.io/PROJECT_ID/selenium/IMAGE:TAG
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      # Do not restart containers after they exit
      restartPolicy: Never
  # of retries before marking as failed.
  backoffLimit: 4