apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test-selenium
  labels:
    app: gke-test-selenium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-test-selenium
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gke-test-selenium
    spec:
      containers:
      - name: gke-test-selenium
        image: gcr.io/grand-radio-307118/selenium/static-site:75b3ef025835afc76bbe78bc90e17331a854f009
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 4000
