apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gke-test-selenium-service
  annotations:
    kubernetes.io/ingress.global-static-ip-name: url-shortener-app-cs6620-selenium-tests
  labels:
    app: gke-test-selenium
spec:
  backend:
    serviceName: gke-test-service-selenium-backend
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gke-test-service-selenium-backend
  labels:
    app: gke-test-selenium
spec:
  type: NodePort
  selector:
    app: gke-test-selenium
  ports:
  - port: 80
    targetPort: 4000
