apiVersion: v1
kind: Service
metadata:
  name: gke-test-staging-service-backend
  labels:
    app: gke-test-staging
spec:
  type: NodePort
  selector:
    app: gke-test-staging
  ports:
  - port: 80
    targetPort: 5000